### ISSUE TITLE
Add summary and aggregation logic for calculating VCNT ANOM_CORR_UNCNTR and ANOM_CORR

### ISSUE THREAD

**Issue by TatianaBurek** [dtcenter/METcalcpy#200]
## Describe the New Feature ##
VCNT ANOM_CORR and ANOM_CORR_UNCNTR were added to MET output in MET-11.0.0-beta1
We should support the  aggregation for these statistics

Only aggregate MCTC ,  MCTS, CTC , CTS tables where the EC_VALUE remains constant

And the derivation of these stats from the Vector partial sums can be seen
here:
https://github.com/dtcenter/MET/blob/c0d6397b88bfcd6b4ae64e289c6c29994f856dc8/src/libcode/vx_statistics/met_stats.cc#L1754

Corresponding issue:
https://github.com/dtcenter/METviewer/issues/403

### Acceptance Testing ###
*List input data types and sources.*
*Describe tests required for new functionality.*

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
2792541

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [ ] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## New Feature Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by TatianaBurek** [comment]
@JohnHalleyGotway 
I added Python implementation of ANOM_CORR and ANOM_CORR_UNCNTR:
https://github.com/dtcenter/METcalcpy/blob/bf53d16b53b67fa6b2b5e995102d919bd737cf4e/metcalcpy/util/vcnt_statistics.py#L516
Could you please verify that I translated C code to Python correctly
https://github.com/dtcenter/MET/blob/c0d6397b88bfcd6b4ae64e289c6c29994f856dc8/src/libcode/vx_statistics/met_stats.cc#L1754

**Comment by JohnHalleyGotway** [comment]
@TatianaBurek, I think the source of the data may not be quite correct. The VCNT anomaly correlation is computed from the VAL1L2 partial sums rather than the VL1L2 partial sums. Judging by [this line](https://github.com/dtcenter/METcalcpy/blob/bf53d16b53b67fa6b2b5e995102d919bd737cf4e/metcalcpy/util/vcnt_statistics.py#L520) I'm guessing you're using the VL1L2 columns as input rather than the VAL1L2 ones. Basically, all the column names should have an 'a' in them, to indicate they are partial sums of the anomalies:
```
        fa_speed_bar = sum_column_data_by_name(input_data, columns_names, 'fa_speed_bar') / total  # f
        oa_speed_bar = sum_column_data_by_name(input_data, columns_names, 'oa_speed_bar') / total  # o
        uvffabar = sum_column_data_by_name(input_data, columns_names, 'uvffabar') / total  # ff
        uvfoabar = sum_column_data_by_name(input_data, columns_names, 'uvfoabar') / total  # fo
        uvooabar = sum_column_data_by_name(input_data, columns_names, 'uvooabar') / total  # oo
```

The rest of the math code seems to match the compute_corr() function in MET well.

Actually, the easiest way to test would be doing some aggregation of VAL1L2 lines in METviewer and computing this ANOM_CORR output. Then perform the exact same aggregate_stat type job in Stat-Analysis. Both should yield the same result. LMK if you'd like any help doing that validation step.

**Comment by TatianaBurek** [comment]
@JohnHalleyGotway  I changed the logic to use VAL1L2 table. Could you please test the stats. 
I used:
http://dakota.rap.ucar.edu:8080/metviewer_dev/
#20220810_131521
The data in the database is from the dataset that you provided for this issue
