### ISSUE TITLE
Fix failed case of test_event_equalize.py

### ISSUE THREAD

**Issue by jprestop** [dtcenter/METcalcpy#250]
## Describe the Problem ##
When running _python3 -m pytest test_event_equalize.py_ in _/apps/sw_review/emc/METcalcpy/METcalcpy-2.0.0/test_ on WCOSS2 Acorn, the following error occurred.  Currently, this error is not reproducible on "seneca".  The assignee will try to recreate the environment on seneca using the nco_metcalcpy_requirements.txt file and the pip_list_METcalcpy_only_acorn.txt.  If this error is still not reproducible, there will be a working session on WCOSS2 Acorn with @jprestop.

```
========================================================================== test session starts ===========================================================================
platform linux -- Python 3.8.6, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /apps/sw_review/emc/METcalcpy/METcalcpy-2.0.0/test, configfile: pytest.ini
collected 4 items                                                                                                                                                        

test_event_equalize.py ...F                                                                                                                                        [100%]

================================================================================ FAILURES ================================================================================
__________________________________________________________________ test_equalize_axis_data_no_fcst_var ___________________________________________________________________

settings_no_fcst_var_vals = {'fix_val_keys': [], 'fix_vals_permuted': {}, 'indy_var': {}, 'line_type': None, ...}

    def test_equalize_axis_data_no_fcst_var(settings_no_fcst_var_vals):
        '''
           conditions that lead to an empty data frame from event equalization should
           return an empty data frame instead of an error due to trying to clean up the 'equalize' column before
           returning the event equalization data frame.
        '''
    
        print("Testing equalize_axis_data with ROC CTC threshold data...")
        input_file_list = ["data/ROC_CTC_thresh.data", "data/ROC_CTC.data"]
        for input_file in input_file_list:
            cur_df = pd.read_csv(input_file, sep='\t')
            fix_vals_keys = []
            fix_vals_permuted_list = []
    
>           ee_df = equalize_axis_data(fix_vals_keys, fix_vals_permuted_list, settings_no_fcst_var_vals, cur_df, axis='1')

test_event_equalize.py:200: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../metcalcpy/util/utils.py:697: in equalize_axis_data
    event_equalize(series_data_for_ee, params['indy_var'],
../metcalcpy/event_equalize.py:65: in event_equalize
    series_data['equalize'] = series_data.loc[:, 'equalize'].astype(str) + " " \
/apps/prod/python-modules/3.8.6/intel/19.1.3.304/lib/python3.8/site-packages/pandas/core/frame.py:3645: in __setitem__
    self._set_item_frame_value(key, value)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self =    fcst_thresh  fy_oy  fy_on  fn_oy  fn_on       fcst_valid_beg  fcst_lead                    equalize
0       >0.635 ... 12:00:00 120000
13      >0.635    122    872    146  25484  2012-04-09 12:00:00     120000  2012-04-09 12:00:00 120000
key = 'equalize'
value =      0    1    2    3    4    5    6    7    8    9    10   11   12   13
0   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  N...N  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
13  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN

    def _set_item_frame_value(self, key, value: DataFrame) -> None:
        self._ensure_valid_index(value)
    
        # align columns
        if key in self.columns:
            loc = self.columns.get_loc(key)
            cols = self.columns[loc]
            len_cols = 1 if is_scalar(cols) else len(cols)
            if len_cols != len(value.columns):
>               raise ValueError("Columns must be same length as key")
E               ValueError: Columns must be same length as key

/apps/prod/python-modules/3.8.6/intel/19.1.3.304/lib/python3.8/site-packages/pandas/core/frame.py:3775: ValueError
-------------------------------------------------------------------------- Captured stdout call --------------------------------------------------------------------------
Testing equalize_axis_data with ROC CTC threshold data...
======================================================================== short test summary info =========================================================================
FAILED test_event_equalize.py::test_equalize_axis_data_no_fcst_var - ValueError: Columns must be same length as key
====================================================================== 1 failed, 3 passed in 2.03s =======================================================================
```

### Expected Behavior ###
All tests should pass.

### Environment ###
Describe your runtime environment:
*1. Machine: WCOSS2 Acorn
*2. OS: SUSE Linux Enterprise Server 15 SP3
*3. Software version number(s): METcalcpy 2.0.0

### To Reproduce ###
Describe the steps to reproduce the behavior: **Already described above**
*1. Go to '...'*
*2. Click on '....'*
*3. Scroll down to '....'*
*4. See error*
*Post relevant sample data following these instructions:*
*https://dtcenter.org/community-code/model-evaluation-tools-met/met-help-desk#ftp*

### Relevant Deadlines ###
ASAP

### Funding Source ###
2792542, 2773542

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Organization** level **Project** for support of the current coordinated release
- [x] Select **Repository** level **Project** for development toward the next official release or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next bugfix version

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Bugfix Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **main_\<Version>**.
Branch name: `bugfix_<Issue Number>_main_<Version>_<Description>`
- [ ] Fix the bug and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **main_\<Version>**.
Pull request: `bugfix <Issue Number> main_<Version> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Organization** level software support **Project** for the current coordinated release
Select: **Milestone** as the next bugfix version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Complete the steps above to fix the bug on the **develop** branch.
Branch name:  `bugfix_<Issue Number>_develop_<Description>`
Pull request: `bugfix <Issue Number> develop <Description>`
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Close this issue.

**Comment by bikegeek** [comment]
This issue is due to a difference in the pandas code.  In pandas 1.5.x, the __setitem__ method has been modified from this (1.2.3):

**pandas 1.2.3**

> if isinstance(key, (Series, np.ndarray, list, Index)):
>     self._setitem_array(key, value)
> elif isinstance(key, DataFrame):
>     self._setitem_frame(key, value)
> else:
>     # set column
>     self._set_item(key, value)
> 

**to this in pandas 1.5.x:**

> if isinstance(key, DataFrame) or getattr(key, "ndim", None) == 2:
>     self._setitem_frame(key, value)
> elif isinstance(key, (Series, np.ndarray, list, Index)):
>     self._setitem_array(key, value)
> elif isinstance(value, DataFrame):
>     self._set_item_frame_value(key, value)
> elif (
>     is_list_like(value)
>     and not self.columns.is_unique
>     and 1 < len(self.columns.get_indexer_for([key])) == len(value)
> ):
>     # Column to set is duplicated
>     self._setitem_array([key], value)
> else:
>     # set column
>     self._set_item(key, value)

In the METcalcpy test_equalize_axis_data_no_fcst_var(), the self.__setitem_frame() is invoked, where this check fails, resulting in the ValueError: 'Columns must be the same length as the key':

_if len_cols != len(value.columns):_

**Comment by bikegeek** [comment]
in test_equalize_axis_data_no_fcst_var, the fixture was setting the indy_var value to an empty dictionary, rather than ''.  Now the event equalization for no fcst_var_vals and empty indy_var returns the input data frame and the ValueError from pandas is no longer raised.  

There is a difference in how this code is being evaluated in the two versions of pandas:
   
in event_equalize.py, lines 64-66:
> if equalize_by_indep and indy_var not in exception_columns:
>         series_data['equalize'] = series_data.loc[:, 'equalize'].astype(str) + " " \
>                                   + series_data.loc[:, indy_var].astype(str)
> 

If indy_var is set to an empty dictionary, the code run under pandas 1.5.x will raise the ValueError as a result of the check in the new code called by __setitem__ in frame.py (pandas).  

Setting the indy_var to '' in the test fixture prevents the .loc operation on a dictionary rather than a string ('', or 'fcst_lead', etc.)
