### ISSUE TITLE
Fix test_scorecard.py with pandas-1.5.1

### ISSUE THREAD

**Issue by jprestop** [dtcenter/METcalcpy#251]
## Describe the Problem ##
Running the pytests on WCOSS2 Acorn produced this error:
```
================================================================================= ERRORS =================================================================================
___________________________________________________________________ ERROR collecting test_scorecard.py ___________________________________________________________________
ImportError while importing test module '/apps/sw_review/emc/METcalcpy/METcalcpy-2.0.0/test/test_scorecard.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/apps/spack/python/3.8.6/intel/19.1.3.304/pjn2nzkjvqgmjw4hmyz43v5x4jbxjzpk/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test_scorecard.py:4: in <module>
    from metcalcpy.scorecard import Scorecard, pd
../metcalcpy/scorecard.py:47: in <module>
    from pandas.core.common import SettingWithCopyWarning
E   ImportError: cannot import name 'SettingWithCopyWarning' from 'pandas.core.common' (/u/julie.prestopnik/.local/lib/python3.8/site-packages/pandas/core/common.py)
======================================================================== short test summary info =========================================================================
ERROR test_scorecard.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
============================================================================ 1 error in 2.23s ============================================================================
```

### Expected Behavior ###
This pytest should pass.

### Environment ###
Describe your runtime environment:
1. Machine: WCOSS2 Acorn
2. OS: SUSE Linux Enterprise Server 15 SP3, Linux alogin01 5.3.18-150300.59.90-default
3. Software version number(s): METcalcpy-2.0.0

### To Reproduce ###
Describe the steps to reproduce the behavior:
*1. Go to '...'*
*2. Click on '....'*
*3. Scroll down to '....'*
*4. See error*
*Post relevant sample data following these instructions:*
*https://dtcenter.org/community-code/model-evaluation-tools-met/met-help-desk#ftp*
Ran _python3 -m pytest_  in /apps/sw_review/emc/METcalcpy/METcalcpy-2.0.0/test

### Relevant Deadlines ###
ASAP

### Funding Source ###
2792542, 2773542

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Organization** level **Project** for support of the current coordinated release
- [x] Select **Repository** level **Project** for development toward the next official release or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next bugfix version

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Bugfix Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **main_\<Version>**.
Branch name: `bugfix_<Issue Number>_main_<Version>_<Description>`
- [ ] Fix the bug and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **main_\<Version>**.
Pull request: `bugfix <Issue Number> main_<Version> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Organization** level software support **Project** for the current coordinated release
Select: **Milestone** as the next bugfix version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Complete the steps above to fix the bug on the **develop** branch.
Branch name:  `bugfix_<Issue Number>_develop_<Description>`
Pull request: `bugfix <Issue Number> develop <Description>`
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Close this issue.

**Comment by bikegeek** [comment]
Found the code where this is occurring.  In the scorecard.py _get_stats_for_derived(self, series, series_to_data), in line318, there is a check for the SettingWithCopyWarning.  In newer versions of pandas, this is no longer defined.  In the pandas.core.common source code, the _SettingWithCopyWarning_ inherits from the Warning base class.  Replacing _SettingWithCopyWarning_ with _Warning_ (in line 318) will eliminate the NameError: name 'SettingWithCopyWarning' which is causing the test in test_scorecard.py to fail.
