### ISSUE TITLE
Review Computation of No-Skill reference line on Reliability Plots

### ISSUE THREAD

**Issue by TaraJensen** [dtcenter/METcalcpy#26]
## Describe the Problem ##
The No-Skill line on the reliability diagram should always be half-way between the skillful line and the climatology line.  Right now METviewer doesn't not always place it there.  This was pointed out by Binbin and Binyu at EMC.  Their reporting of the issue can be found on the[ METplus Users meeting notes](https://docs.google.com/document/d/1AXchk4vs5kI1Jk4PthglFaFOUeeIBIhkfLLafQclJ04/edit) from 9/21/2020

### Expected Behavior ###
See [Ensemble Forecast Verification Slides 11-16](https://www.swpc.noaa.gov/sites/default/files/images/u30/Ensemble%20Forecast%20Verification.pdf) for expected behavior (slide 16 shows where the no-skill line) 

### Environment ###
Describe your runtime environment:
*1. Machine: AWS or Linux server
*2. OS: whatever is on AWS and Mohawk
*3. METviewer 3.1

### To Reproduce ###
Describe the steps to reproduce the behavior:
*1. Go to '...'*
*2. Click on '....'*
*3. Scroll down to '....'*
*4. See error*
*Post relevant sample data following these instructions:*
*https://dtcenter.org/community-code/model-evaluation-tools-met/met-help-desk#ftp*

### Relevant Deadlines ###
This is a bug and needs priority attention.  It probably needs to be updated in both METviewer R and here.  I'll be linking this to METviewer

### Funding Source ###
2790541

### Assignee ###
- [x ] Select **engineer(s)** or **no engineer** required
- [x ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [X ] Select **component(s)**
- [X ] Select **priority**
- [X ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [ ] Select **milestone** to relevant bugfix version

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ]  [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), 

## Bugfix Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **main_\<Version>**.
Branch name: `bugfix_<Issue Number>_main_<Version>_<Description>`
- [ ] Fix the bug and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **main_\<Version>**.
Pull request: `bugfix <Issue Number> main_<Version> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Complete the steps above to fix the bug on the **develop** branch.
Branch name:  `bugfix_<Issue Number>_develop_<Description>`
Pull request: `bugfix <Issue Number> develop <Description>`
- [ ] Close this issue.

**Comment by TatianaBurek** [comment]
this is a part of #48 and was implemented
