### ISSUE TITLE
enhancing the bootstrapping to support circular temporal block bootstrap

### ISSUE THREAD

**Issue by bikegeek** [dtcenter/METcalcpy#3]
Account Key:
2702691 - Work with Eric on how to implement

**Comment by TatianaBurek** [comment]
Here is the article that Eric wrote:
https://doi.org/10.1175/JTECH-D-20-0069.1
He suggested to evaluate his new bootstrap code the  from the R package “distillery” and include it into METcalcpy as a default bootstrap method

**Comment by TatianaBurek** [comment]
Add block.length - Number giving the desired block lengths to 'event_equalize' method and use it to do IID resamples.
