### ISSUE TITLE
Test vertical_interp invocation with MET python embedding

### ISSUE THREAD

**Issue by dwfncar** [dtcenter/METcalcpy#34]
This is a sub-issue of #feature_20_vertical_interp

## Describe the Sub-Issue ##
*Provide a description of the sub-issue here.*
Test vertical_interp output with GridStat.
Embed vertical_interp in GridStat.

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*
3 days

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
David Fillmore
- [ ] Select **scientist(s)** or **no scientist** required
Mrinal Biswas

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [ ] Select **milestone** to next major version milestone or "Future Versions"

**Comment by bikegeek** [comment]
David will contact Mrinal and verify whether this is still necessary.

**Comment by dwfncar** [comment]
First, fix valid_time so that output of vertical_interp can be read by GridDiag.

**Comment by bikegeek** [comment]
move calculation for radial and tangential winds out of the METplotpy plot_cross_section.py and put that support in METcalcpy package.  Re-test to verify that all output will still create the expected radial and tangential wind cross-section plots.
