### ISSUE TITLE
Consider using only .yml or only .yaml extensions

### ISSUE THREAD

**Issue by jprestop** [dtcenter/METcalcpy#349]
## Describe the Task ##
When working on #345 it was noted that there are both .yml files and .yaml files, in the repository, which was a source of some confusion. Considering renaming files (and changing any references to those files) for consistency.

```
jpresto$ find . -name "*yml"
./.github/workflows/release-checksum.yml
./.github/workflows/unit_tests.yml
./.github/workflows/trigger_metplus.yml
./.github/workflows/documentation.yml

jpresto$ find . -name "*yaml"
./examples/read_files.yaml
./examples/vertical_interp_merra2.yaml
./examples/grid_diag_gfs.yaml
./examples/height_from_pressure_merra2.yaml
./examples/height_from_pressure_tcrmw.yaml
./examples/vertical_interp_hwrf.yaml
./.github/workflows/vulnerabilities.yaml
./.readthedocs.yaml

```

### Time Estimate ###
1 to 3 days of work.

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
NONE

### Funding Source ###
TBD

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED CYCLE ASSIGNMENT** label
- [ ] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by hankenstein2** [comment]
Current recommendation is yaml

**Comment by mollybsmith-noaa** [comment]
This is done for METcalcpy.

**Comment by JohnHalleyGotway** [comment]
Please make this same change to the GitHub action workflow names in the `main_v2.1` branch to make the GHA workflow dispatch options more clear.
```
ls .github/workflows/*
```
