### ISSUE TITLE
Design first guess framework for reading in data and handing off to METplotpy and METviewer

### ISSUE THREAD

**Issue by fisherhucar** [dtcenter/METcalcpy#8]
*Replace italics below with details for this issue.*

## Describe the Task ##
Design a collection of classes and inheritance for reading in data, converting to a python dictionary and then either handing directly to METplotpy or turning into an ascii file for METviewer

### Time Estimate ###
2 un-interrupted days

### Sub-Issues ###
- [x] Github Issue #9 

### Relevant Deadlines ###
NONE 

### Funding Source ###
NONE

### Assignee ###
- [x] Select **engineer
- [ ] Select **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Review **projects** and select relevant **Repository** and **Organization** ones
- [ ] Select **milestone**

**Comment by hankenstein2** [comment]
Created a UML diagram, got lots of feedback and will start coding now.
